// Generated by CoffeeScript 1.7.1
(function() {
  var btn, iframe, iframeOrigin, iframePath, log, msg, qs;

  iframeOrigin = "http://127.0.0.1:3030";

  iframePath = iframeOrigin + "/dart-iframe/web/iframe.html";

  qs = document.querySelector.bind(document);

  msg = qs("#compose-message");

  btn = qs("#send-message");

  iframe = qs("#dart-iframe").contentWindow;

  log = qs("#message-log");

  btn.addEventListener("click", function(evt) {
    return iframe.postMessage(msg.value, iframeOrigin);
  });

  window.addEventListener("message", function(evt) {
    var li;
    if (evt.origin === iframeOrigin) {
      li = document.createElement("li");
      li.innerHTML = evt.data;
      console.log(li);
      return log.appendChild(li);
    } else {
      return console.log("Message received from elsewhere: " + evt.origin);
    }
  });

}).call(this);
